### ISSUE TITLE
Kelp unable to decode horizon Problem:EOF continually

### ISSUE THREAD

**Issue by Reidmcc** [lightyeario/kelp#62] opened 2018-11-21 13:58 UTC
## Describe the bug

As of 05:43 CST this morning, 11/21/2018, my Kelp bot is returning `error decoding horizon.Problem: EOF` for nearly every attempted horizon call. Immediately before the consistent failure a `tx_bad_seq` error occurred.  The first errored out cycle log was:

````
2018/11/21 05:43:16 (async) error: tx_bad_seq, setting flag to reload seq number
2018/11/21 05:43:16 (async) error: result code details: tx code = tx_bad_seq , opcodes = []
2018/11/21 05:43:16 ----------------------------------------------------------------------------------------------------
2018/11/21 05:43:16 sleeping for 4m47.670314655s...
2018/11/21 05:48:04 intervalTimeController tickInterval=5m0s, shouldUpdate=true, elapsedSinceUpdate=5m0.000081616s
2018/11/21 05:49:03 error decoding horizon.Problem: EOF
2018/11/21 05:50:03 Can't load offers: error decoding horizon.Problem: EOF
2018/11/21 05:50:03 error decoding horizon.Problem: EOF
2018/11/21 05:51:03 Can't load offers: error decoding horizon.Problem: EOF
2018/11/21 05:51:03 error: cannot load offers to compute liabilities for asset (SLT:GCKA6K5PCQ6PNF5RQBF7PQDJWRHO6UOGFMRLK3DYHDOI244V47XKQ4GP): error decoding horizon.Problem: EOF
2018/11/21 05:51:03 liabilities after resetting
2018/11/21 05:52:03 Can't load offers: error decoding horizon.Problem: EOF
2018/11/21 05:52:03 error: cannot load offers to compute liabilities for asset (SLT:GCKA6K5PCQ6PNF5RQBF7PQDJWRHO6UOGFMRLK3DYHDOI244V47XKQ4GP): error decoding horizon.Problem: EOF
2018/11/21 05:52:03 could not fetch liability for asset 'base  ', error = error decoding horizon.Problem: EOF
2018/11/21 05:53:03 Can't load offers: error decoding horizon.Problem: EOF
2018/11/21 05:53:03 error: cannot load offers to compute liabilities for asset (native): error decoding horizon.Problem: EOF
2018/11/21 05:53:03 could not fetch liability for asset 'quote ', error = error decoding horizon.Problem: EOF
2018/11/21 05:53:03 error decoding horizon.Problem: EOF
2018/11/21 05:53:03 deleting all offers
2018/11/21 05:53:03 created 39 operations to delete offers
2018/11/21 05:53:03 reloading sequence number
2018/11/21 05:54:03 error getting seq num: load account failed: error decoding horizon.Problem: EOF
2018/11/21 05:54:03 tx XDR: AAAAAFEaM7CTwKol9+ZL7WdPTrZNPY0g0gWj8WWIZI9mhpEOAAAPPAEgurgAABVEAAAAAAAAAAAAAAAnAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAA0gRokAmJaAAAAAAALLlCgAAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAABqRmqwBMS0AAAAAAAsuUJgAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAANUwPBAJiWgAAAAAACy5QpAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAAGuOlkAExLQAAAAAALLlCoAAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAAAIoWCwAGGoAAAAAAAsuUJwAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAGzap1AExLQAAAAAACy5QrAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAANpcqcAJiWgAAAAAALLm6sAAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAAA26yWwAmJaAAAAAAAsubrAAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAG5/YLAExLQAAAAAACy5utAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAA3aih0AmJaAAAAAAALLm64AAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAABv8O4wBMS0AAAAAAAsubrwAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAOBU47AJiWgAAAAAACy5uwAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAAC0i1cAB6EgAAAAAALLm7EAAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAABxLdLQBMS0AAAAAAAsubsgAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAA5Gb5AAmJaAAAAAACy6UiAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAALfSBMAHoSAAAAAAALLpSMAAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAABz7NkwBMS0AAAAAAAsulJAAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAO16AnAJiWgAAAAAACy66eAAAAAAAAAAMAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAAAAAd3OxUATEtAAAAAAALLrp8AAAAAAAAAAwAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAAAAAB4h9AABMS0AAAAAAsuuoAAAAAAAAAADAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAAAPKCsDAJiWgAAAAAACy66hAAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAADfDsATEtAAAAAAALLlB4AAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAOlMwBMS0AAAAAAAsuUGwAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAB0//AJiWgAAAAAACy5QcAAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAHWzsAmJaAAAAAAALLntkAAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAA7BwAExLQAAAAAAsuh8wAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAB2aJAJiWgAAAAAACy6H0AAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAAAw8AAD6AAAAAAALLofUAAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAeOpQCYloAAAAAAAsuh9gAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAA8o5AExLQAAAAAACy6hGAAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAHmkMAmJaAAAAAAALLqEcAAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAD0AwATEtAAAAAAAsuoSAAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAB6vRAJiWgAAAAAACy6hJAAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAD280ATEtAAAAAAALLqEoAAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAGP4QAehIAAAAAAAsuoSwAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAB9VjAJiWgAAAAAACy6hMAAAAAAAAAAMAAAAAAAAAAVNMVAAAAAAAlA8rrxQ89pexgEv3wGm0Tu9RxisitWx4ONyNc5Xn7qgAAAAAAAAAAAAH858AmJaAAAAAAALLqE0AAAAAAAAAAwAAAAAAAAABU0xUAAAAAACUDyuvFDz2l7GAS/fAabRO71HGKyK1bHg43I1zlefuqAAAAAAAAAAAAAf5uQCYloAAAAAAAsuoTgAAAAAAAAADAAAAAAAAAAFTTFQAAAAAAJQPK68UPPaXsYBL98BptE7vUcYrIrVseDjcjXOV5+6oAAAAAAAAAAAAAP/7ABMS0AAAAAACy6hPAAAAAAAAAAFmhpEOAAAAQDxFLGrtAeyuRXaMNWp9tG9IxhrGv7yYbi9yM8lKayXCkY1Y92vB61AZVkZCh+SXrm/m8VOdP4fBalMBhqzoigk=
2018/11/21 05:54:03 submitting tx XDR to network (async)
2018/11/21 05:55:03 (async) error: tx failed for unknown reason, error message: error decoding horizon.Problem: EOF
2018/11/21 05:55:03 ----------------------------------------------------------------------------------------------------
````

## Expected behavior
Horizon calls should work.

## Frequency

As of now it's always. The bot had been running for about 13 hours successfully before the errors started.

## Steps To Reproduce

On my end just try to start the bot, it will only get as far as trying to validate trustlines and then return `error decoding horizon.Problem: EOF` Update: when I retried one more time before submitting this issue it got past validating trustlines and failed at loading offers.

## Possible Solution

I think this is probably a server side issue but I wanted to report it because it's continual now and I wouldn't expect horizon to be down for 2+ hours. I don't know what would be wrong client side.

## Your Environment

  version: bal_reserve:v1.1.1-32-g4b6b46e9-dirty
  git branch: bal_reserve
  git hash: 4b6b46e971bca7f0269aa951eee27a4e88df8f0b-dirty
  build date: 20181120T001603Z
  GOOS: linux
  GOARCH: amd64

## Context

The bot does not function in this state.

**Comment by Reidmcc** [comment] 2018-11-21 16:17
Just saw on Reddit that there's apparently a DDOS attack on SDF's Horizon servers, so that's probably the cause of this. I'm going to leave this open until I'm up and running again in case that's not it.

Which brings up a point; I see activity on StellarX while this is going on. Does Interstellar run its own Horizon server? If so it might be worth considering it as an option for Kelp.

**Comment by nikhilsaraf** [comment] 2018-11-21 23:21
You can configure your horizon endpoint in the _trader.conf_ file. Kelp is handling these failures correctly because these errors are not causing Kelp to crash. Whenever the horizon server is back up the bot would continue it's trading activities.

If we were to use another service then that service would suffer the same possible downtime as public horizon in the event of a DDOS attack. The right approach here would be to run your own horizon server and point Kelp to that service.

This issue is related to what was previously reported when Kelp would crash in such scenarios, which has since been fixed: https://github.com/lightyeario/kelp/issues/43

This is not a bug, closing this issue. Feel free to reopen if you think it's still an issue.

**Closed by nikhilsaraf** 2018-11-21 23:21 UTC
